"""
Core data models and enums for the Dual-Engine Strategy System.

This module defines the fundamental data structures for the dual-engine trading system
that operates two independent engines: Core Strategy Engine (institutional liquidity model)
and Quick Scalp Engine (M1 momentum-based scalping).

Requirements: 27.1, 27.5
"""

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import List, Optional, Dict


class Instrument(Enum):
    """Trading instruments supported by the dual-engine system."""
    US30 = "US30"
    XAUUSD = "XAUUSD"
    NAS100 = "NAS100"


class Direction(Enum):
    """Trade direction for signals and positions."""
    LONG = "LONG"
    SHORT = "SHORT"


class EngineType(Enum):
    """Trading engine types in the dual-engine system."""
    CORE_STRATEGY = "CORE_STRATEGY"
    QUICK_SCALP = "QUICK_SCALP"


class SessionType(Enum):
    """Active trading session types for Quick Scalp Engine."""
    LONDON = "LONDON"
    NY_OPEN = "NY_OPEN"
    POWER_HOUR = "POWER_HOUR"


class SignalGrade(Enum):
    """Signal quality grading for Core Strategy Engine."""
    A_PLUS = "A+"
    A = "A"
    B = "B"


@dataclass
class OHLCVBar:
    """OHLCV market data bar for a specific timestamp."""
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float


@dataclass
class TimeframeData:
    """Market data for a specific instrument and timeframe."""
    instrument: Instrument
    timeframe: str  # "W", "D", "H4", "H1", "M5", "M1"
    bars: List[OHLCVBar]


@dataclass
class HTFAlignmentScore:
    """Higher timeframe alignment score breakdown (max 20 points)."""
    total: int  # 0-20
    weekly: int  # 0-6
    daily: int  # 0-6
    h4: int  # 0-4
    h1: int  # 0-4


@dataclass
class ConfluenceScore:
    """Complete confluence score breakdown for Core Strategy Engine (max 100 points)."""
    total: int  # 0-100
    htf_alignment: int  # 0-20
    key_level: int  # 0-15
    liquidity_sweep: int  # 0-15
    fvg: int  # 0-15
    displacement: int  # 0-10
    mss: int  # 0-10
    vwap: int  # 0-5
    volume_spike: int  # 0-5
    atr: int  # 0-5
    htf_target: int  # 0-5
    session: int  # 0-5
    spread: int  # 0-5


@dataclass
class CoreSignal:
    """Trading signal generated by Core Strategy Engine."""
    instrument: Instrument
    direction: Direction
    entry_price: float
    stop_loss: float
    tp1: float  # Take profit 1 at 1R
    tp2: float  # Take profit 2 at 2R
    confluence_score: ConfluenceScore
    grade: SignalGrade
    timestamp: datetime


@dataclass
class ScalpSignal:
    """Trading signal generated by Quick Scalp Engine."""
    instrument: Instrument
    direction: Direction
    entry_price: float
    stop_loss: float
    take_profit: float  # Single TP at 0.8-1R
    session: SessionType
    timestamp: datetime


@dataclass
class Position:
    """Active trading position for either engine."""
    position_id: str
    engine: EngineType
    instrument: Instrument
    direction: Direction
    entry_price: float
    stop_loss: float
    size: float
    remaining_size: float
    tp1_hit: bool
    tp2_hit: bool
    trailing_active: bool


@dataclass
class TradeOutcome:
    """Result of a completed trade."""
    trade_id: str
    win: bool
    r_multiple: float
    profit_loss: float


@dataclass
class PerformanceMetrics:
    """Performance metrics for an engine."""
    win_rate: float
    profit_factor: float
    average_rr: float
    total_trades: int
    winning_trades: int
    losing_trades: int


@dataclass
class RiskPoolStatus:
    """Risk pool status for an engine."""
    engine: EngineType
    daily_trade_count: int
    daily_drawdown: float
    consecutive_losses: int
    session_counts: Dict[SessionType, int]  # Session-specific trade counts


@dataclass
class Configuration:
    """System configuration for dual-engine strategy system."""
    instruments: List[Instrument]
    signal_window_start: str  # "10:00"
    signal_window_end: str  # "22:00"
    core_risk_per_trade: float  # 0.01 (1%)
    core_max_daily_trades: int  # 2
    core_max_daily_drawdown: float  # 0.02 (2%)
    scalp_risk_per_trade_min: float  # 0.0025 (0.25%)
    scalp_risk_per_trade_max: float  # 0.005 (0.5%)
    scalp_session_limits: Dict[SessionType, int]  # Session-specific trade limits
    spread_limits_global: Dict[Instrument, float]  # Global spread limits
    spread_limits_scalp: Dict[Instrument, float]  # Scalp-specific spread limits
    slippage_limit: float  # 10 points
    news_buffer_before: int  # 30 minutes
    news_buffer_after: int  # 60 minutes
